/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import businesslogic.model.MenaceGame;
import businesslogic.util.CSVutil;
import businesslogic.util.DB4OUtil;
import javax.swing.JButton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import userinterface.play.PlayJPanel;
import userinterface.train.TrainJPanel;

/**
 *
 * @author manojreddy
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private static final Logger logger = LoggerFactory.getLogger(MainJFrame.class);
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private MenaceGame menaceGame;
    
    public MainJFrame() {
        initComponents();
        logger.info("Trying to retrive Trained states from DBo4");
        menaceGame = CSVutil.getTrainedMenaceGameFromCSV();
        
        this.setSize(1680, 1050);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainjSplitPane = new javax.swing.JSplitPane();
        leftjPanel = new javax.swing.JPanel();
        trainjButton = new javax.swing.JButton();
        playjButton = new javax.swing.JButton();
        rightjPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        trainjButton.setText("Train");
        trainjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainjButtonActionPerformed(evt);
            }
        });

        playjButton.setText("Play");
        playjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftjPanelLayout = new javax.swing.GroupLayout(leftjPanel);
        leftjPanel.setLayout(leftjPanelLayout);
        leftjPanelLayout.setHorizontalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(playjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftjPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(trainjButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        leftjPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {playjButton, trainjButton});

        leftjPanelLayout.setVerticalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(trainjButton)
                .addGap(18, 18, 18)
                .addComponent(playjButton)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        leftjPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {playjButton, trainjButton});

        mainjSplitPane.setLeftComponent(leftjPanel);

        javax.swing.GroupLayout rightjPanelLayout = new javax.swing.GroupLayout(rightjPanel);
        rightjPanel.setLayout(rightjPanelLayout);
        rightjPanelLayout.setHorizontalGroup(
            rightjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        rightjPanelLayout.setVerticalGroup(
            rightjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        mainjSplitPane.setRightComponent(rightjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trainjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainjButtonActionPerformed
        // TODO add your handling code here:
        TrainJPanel trainJPanel= new TrainJPanel(menaceGame, this);
        mainjSplitPane.setRightComponent(trainJPanel);
    }//GEN-LAST:event_trainjButtonActionPerformed

    private void playjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playjButtonActionPerformed
        // TODO add your handling code here:
        PlayJPanel playJPanel= new PlayJPanel(menaceGame);
        mainjSplitPane.setRightComponent(playJPanel);
    }//GEN-LAST:event_playjButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        logger.info("Windowclosed");
//        dB4OUtil.storeGameState(menaceGame);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    public JButton getPlayjButton() {
        return playjButton;
    }

    public JButton getTrainjButton() {
        return trainjButton;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftjPanel;
    private javax.swing.JSplitPane mainjSplitPane;
    private javax.swing.JButton playjButton;
    private javax.swing.JPanel rightjPanel;
    private javax.swing.JButton trainjButton;
    // End of variables declaration//GEN-END:variables
}
