/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package userinterface.train;

import businesslogic.model.MenaceGame;
import businesslogic.logic.MenaceSelfTrain;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import userinterface.MainJFrame;

/**
 *
 * @author anshitaverma
 */
public class TrainJPanel extends javax.swing.JPanel {
    
    private MenaceGame menaceGame;
     private static final Logger logger = LoggerFactory.getLogger(TrainJPanel.class);
    
    /** Creates new form TrainJPanel */
    public TrainJPanel() {
        initComponents();
    }

    public TrainJPanel(MenaceGame menaceGame) {
        this.menaceGame=menaceGame;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        trainjbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        iterationsCountField = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        trainjbutton.setBackground(new java.awt.Color(0, 0, 0));
        trainjbutton.setForeground(new java.awt.Color(255, 255, 255));
        trainjbutton.setText("Train");
        trainjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainjbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Number of Iterations:");

        iterationsCountField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        iterationsCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterationsCountFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iterationsCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(trainjbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iterationsCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(trainjbutton)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iterationsCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iterationsCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iterationsCountFieldActionPerformed

    private void trainjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainjbuttonActionPerformed
        // TODO add your handling code here:
        String iterationCount= iterationsCountField.getText();

        try{
            int iterations= Integer.parseInt(iterationCount);
            //TODO: need to call function for training
            MenaceSelfTrain menaceSelfTrain=new MenaceSelfTrain(menaceGame,iterations);
            menaceSelfTrain.selfPlay();
        }
        catch(Exception e){
            logger.info("Conversion from string to integer failed from user input");
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Number"); 
        } 
        
        
        
    }//GEN-LAST:event_trainjbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iterationsCountField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton trainjbutton;
    // End of variables declaration//GEN-END:variables

}
